name: Github Actions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
    - name: Npm install
      run: npm install |
        npm install -g vsce
    - name: Npm Build
      run: npm build
#     Disabled until test are added 
#     - name: Npm test
#       run: npm test  
